name: Deploy

concurrency:
  group: build
  cancel-in-progress: false

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image for backend and frontend
        run: |
          docker build --platform=linux/amd64 --build-arg skip_dev_deps=true .
